### PR TITLE
Fix#1182

### LINKED ISSUE #1182: The SI Details activity is not working in a good manner.
**Summary:**

The SI Details activity is not working in a good manner because when we press edit details and  press back button, it simply exits the activity, nothing extra, there is an absence of that extra transition.

**Steps to reproduce:**

1. Go to SI details,
2. Press edit float button,
3. Try to edit or maybe not,
4. Now press back and if you edited it then it asks you to accept discard changes and simply exits, if not then it simply exits activity.

**Expected behavior:**

It should go back to the none editable state first and after that exit should come into picture.

**Observed behavior:**

It simply exits the activity right now.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

https://user-images.githubusercontent.com/56648862/106005254-0badab00-60da-11eb-8ae8-257c77ad88f7.mp4

### PR DESCRIPTION
**Pull request by EGOR-IND**
## Issue Fix
Fixes #1182 

## Screenshots

https://user-images.githubusercontent.com/56648862/106306340-ed83ae80-6283-11eb-9e24-5a0efb79a7e8.mp4

## Description
enhanced the transition between view and edit state of SI Details activity.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by EGOR-IND** [comment]
@devansh-299 review this one, and also please give your thoughts about issue #1183.

**Comment by EGOR-IND** [comment]
@devansh-299 review this when you're free.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt [hunk 1]
```diff
@@ -267,13 +261,51 @@ class SIDetailsActivity : BaseActivity(), StandingInstructionContract.SIDetailsV
     private fun showDiscardChangesDialog() {
         val dialogBox = DialogBox()
         dialogBox.setOnPositiveListener { dialog, which ->
+            fab.hide()
             dialog.dismiss()
-            finish()
+            editDetails(false);
```
Comment (devansh-299) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt]: please remove `;`  xD, also why removing `finish()` and making effort to re-set the textviews when we simply need to exit the activity on clicking _accept_

**Review by devansh-299 — CHANGES_REQUESTED** [review]

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt (hunk 1 above)
Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt]: Oooh sorry for that I got with the flow of java I made this mistake several times during this, I think I left one here😄, I'll resolve it in few minutes.

**Comment by EGOR-IND** [comment]
sergeant @devansh-299, made the changes you requested sir, review this sir, over n out XD.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt (hunk 1 above)
Comment (devansh-299) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt]: @EGOR-IND can you explain the reasoning behind the _re-setting_ of textviews before exiting and removing the `finish()` line, I might be missing something.

Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/SIDetailsActivity.kt]: Yeah, for sure,  the reason why i removed finish() from the positive button of dialog box is that it was directly exiting the activity, which was the whole purpose of this PR making the exiting experience more better, so when user accept discarding changes then they will first go to the read only version of activity and then they can exit. You can see what my changes are doing from the video😊.
