### PR TITLE
Fix: Not displaying all transactions on button click

### LINKED ISSUE #1516: Bug: All transactions are not displayed when clicking "All" filter button
**Summary:**

Initially all the transactions are displayed. But clicking on the other filter buttons and again clicking on "All" filter button doesn't show any transactions

**Steps to reproduce:**

Go to History tabs. Click on "Credit" "Debit" filters and then click on "All" filter.

**Expected behavior:**

Display all the transactions.

**Observed behavior:**

Not displaying all the transactions made.

**Device and Android version:**

Device-Samsung A51 Android-13

**Screenshots:**

https://github.com/openMF/mobile-wallet/assets/91717339/8ec0041e-7a54-4261-a2a0-2badf87210bb

### PR DESCRIPTION
**Pull request by devrahul-2508**
## Issue Fix
Fixes #1516 

## Screenshots

https://github.com/openMF/mobile-wallet/assets/91717339/91bd6120-b246-47d4-b63b-67d97bdfbfc4

## Description
Added an extra check if the filter type is "All" then display all credit and debit transactions

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt [hunk 1]
```diff
@@ -72,16 +72,28 @@ class HistoryPresenter @Inject constructor(
 
     override fun filterTransactionType(type: TransactionType?) {
         val filterTransactions: MutableList<Transaction> = ArrayList()
-        for (transaction in allTransactions!!) {
-            if (transaction.transactionType == type) {
-                filterTransactions.add(transaction)
+        if(type!=null){
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt]: I think someone while migrating java to kotlin have made this nullable but this would not be nullabe, please remove and format and update the PR.

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt (hunk 1 above)
Comment (devrahul-2508) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/history/presenter/HistoryPresenter.kt]: @therajanmaurya I have updated the PR. Can u please check.

**Review by therajanmaurya — APPROVED** [review]
