### PR TITLE
fix : App crashing on first build

### LINKED ISSUE #293: App crashes on first build
**Summary:**

After importing the project in Android studio, while running for the first time the app crashes throwing Null pointer expection in `MifosPayInstanceIdService.java` and works fine in next tries.

 **Steps to reproduce:**

- Build the project

- Run the app for first time ( Make sure your Internet is on )

**Expected behavior:**

App should not crash.

**Observed behavior:**

While running for the first time the app crashes throwing this exception
`java.lang.NullPointerException
        at org.mifos.mobilewallet.mifospay.data.firebase.api.services.MifosPayInstanceIDService.onTokenRefresh(MifosPayInstanceIDService.java:52)` 
and it runs without crash in next time. 

**Device and Android version:**

Device Model : Asus zenfone 5
Android version : 4.4.0

**Screenshots:**

**On first build**
screenshot_2019-02-12-15-37-22
**On next try**
screenshot_2019-02-12-15-37-35

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #293 

Please make sure these boxes are checked before submitting your pull request - thanks!
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@luckyman20 @ankurs287 Can you please review this PR?

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java [hunk 1]
```diff
@@ -44,23 +44,25 @@
...
-        // Saving reg id to shared preferences
-        mPreferencesHelper.setFirebaseRegId(refreshedToken);
+            // Saving reg id to shared preferences
+            mPreferencesHelper.setFirebaseRegId(refreshedToken);
 
-        // If you want to send messages to this application instance or
-        // manage this apps subscriptions on the server side, send the
-        // Instance ID token to your app server.
-        sendRegistrationToServer(refreshedToken);
+            // If you want to send messages to this application instance or
```
Comment (luckyman20) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: Remove unnecessary changes.

**Comment by RajaVamsi11** [comment]
@luckyman20 Done.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java (hunk 1 above)
Comment (RajaVamsi11) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: ok

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java [hunk 2]
```diff
@@ -44,6 +44,7 @@
     // [START refresh_token]
     @Override
     public void onTokenRefresh() {
+        if(mPreferencesHelper != null){
```
Comment (luckyman20) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]:
```suggestion
        if(mPreferencesHelper != null) {
```

**Comment by RajaVamsi11** [comment]
@luckyman20 Updated.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java [hunk 3]
```diff
@@ -44,6 +44,7 @@
     // [START refresh_token]
     @Override
     public void onTokenRefresh() {
+        if(mPreferencesHelper != null) {
```
Comment (luckyman20) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: What if it will be `null`? Please explain.

Comment (RajaVamsi11) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: Simply it will throw Null Pointer exception when it is null. When the PreferenceHelper object is initialized it contains nothing and here we are calling setFireBaseRegId(refreshedToken) on that object. As it contains nothing, it is throwing Null pointer exception.

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I change documentation according to the newly documented files? Adding space is breaking the fix. If we change documentation accordingly it will be fine. What do you say?

**Comment by luckyman20** [comment]
Looks good to me. @RajaVamsi11 For getting the indentation right, first select all the code (`Ctrl + A`) and then format the code (`Ctrl + Alt + L`).

**Comment by RajaVamsi11** [comment]
@luckyman20 I think the code is properly intended to the changes I made. I checked it using (ctrl+alt+L).

**Comment by luckyman20** [comment]
Yeah now it is properly intended, I was talking for future changes.

**Comment by RajaVamsi11** [comment]
@luckyman20  Ok, thank you. I think it is safe to merge the PR now. What do you say?

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java (hunk 3 above)
Comment (naman14) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: This is incorrect.

The app crashes on first time since it is null and it doesn't crashes next time since `onTokenRefresh` is not even called. (Its only called when the token actually refreshes e.g. new install, app update etc).

See the comment in PR for more details

**Comment by naman14** [comment]
@RajaVamsi11 This is not a fix
You are just checking if `mPreferencesHelper` is not null.

The actual issue here is that the dependency is not being injected anywhere so `mPreferencesHelper` will always be null and not just first time, its just that onTokenRefresh is only called first time

You need to inject the `PreferencesHelper` in constructor

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java [hunk 4]
```diff
@@ -44,17 +44,19 @@
...
-        Log.d(TAG, "Refreshed token: " + refreshedToken);
-
-        // Saving reg id to shared preferences
-        mPreferencesHelper.setFirebaseRegId(refreshedToken);
-
-        // If you want to send messages to this application instance or
-        // manage this apps subscriptions on the server side, send the
-        // Instance ID token to your app server.
-        sendRegistrationToServer(refreshedToken);
+        if (mPreferencesHelper != null) {
```
Comment (naman14) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: Remove this check and inject `mPreferencesHelper` properly

Comment (RajaVamsi11) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: Done

**Comment by RajaVamsi11** [comment]
@naman14  Updated according to the changes suggested. Can you please review the PR.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java [hunk 5]
```diff
@@ -32,9 +32,12 @@
 public class MifosPayInstanceIDService extends FirebaseInstanceIdService {
 
     private static final String TAG = "MyFirebaseIIDService";
+    private final PreferencesHelper mPreferencesHelper;
 
     @Inject
-    PreferencesHelper mPreferencesHelper;
+    public MifosPayInstanceIDService(PreferencesHelper mPreferencesHelper) {
```
Comment (naman14) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/data/firebase/api/services/MifosPayInstanceIDService.java]: `FirebaseInstanceIdService` needs a zero args constructor so you cant provide a constructor that has `PreferencesHelper` argument. (It will only call the zero arg constructor, will also be crashing in your latest change)

Instead do it like this - 
```
    @Inject
    PreferencesHelper mPreferencesHelper;

    public MifosPayInstanceIDService() {
        MifosPayApp.get(MifosPayApp.getContext()).component().inject(this);
    }
```

And add this method in `ApplicationComponent`
```
    void inject(MifosPayInstanceIDService mifosPayInstanceIDService);
```

**Comment by RajaVamsi11** [comment]
@naman14 Updated.
