### PR TITLE
Fix: #83 User's profile image is circle now

### LINKED ISSUE #83: Bug: User's profile picture isn't rounded when profile image's changed
**Summary:**

User's profile image should be always rounded.

**Steps to reproduce:**

Dashboard > Profile > Edit Profile > Change profile picture

**Expected behavior:**

Rounded profile image

**Observed behavior:**

The image is a rectangle shape.

**Device and Android version:**

Huawei p10, Android 8.0

**Screenshots:**

### PR DESCRIPTION
**Pull request by letelete**
Fixes #83 

Please Add Screenshots If any UI changes.

9033a907-65ee-44b3-a921-e24fa8cf0939

Please Add Summary of what changes you have made. (Optional)

User's profile image is circle now, hooray!

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java [hunk 1]
```diff
@@ -457,8 +456,10 @@ public void setMobile(String mobile) {
 
     @Override
     public void setImage(String fullName) {
-        TextDrawable drawable = TextDrawable.builder().buildRound(fullName.substring(0, 1),
-                R.color.colorPrimary);
+        TextDrawable drawable = TextDrawable.builder().beginConfig()
```
Comment (letelete) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java]: Btw. I had to change the way how TextDrawable is building, because of blank space error while was trying to set a TextDrawable as an ImageDrawable to the CircleImageView. Adding height and width fix the problem.
