### PR TITLE
fix: #1169 Added option to scan qr code in Create SI Activity

### LINKED ISSUE #1169: Add QR option in Create Standing Instruction Activity
**Summary:**
Add QR option in Create Standing Instruction Activity

**Steps to reproduce:**
1. Open Payments section
2. Open the SI tab
3. Click on the add FAB button
4. Observe

**Expected behavior:**
Additional option to enter VPA using QR scanner instead of entering manually.

**Observed behavior:**
VPA can only be entered manually.

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

WhatsApp Image 2021-01-18 at 1 54 37 PM

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #1169

## Screenshots

https://user-images.githubusercontent.com/50913976/106180798-cb762780-61c2-11eb-99cd-00103c78e0c2.mp4

## Description
Added option to scan QR code

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
@devansh-299 Can you please review this.

**Review by EGOR-IND — APPROVED** [review]
A good one, looks fine to me.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt [hunk 1]
```diff
@@ -110,6 +121,56 @@ class NewSIActivity : BaseActivity(), StandingInstructionContract.NewSIView {
         ll_create_si.visibility = View.VISIBLE
     }
 
+    @OnClick(R.id.btn_scan_qr)
```
Comment (s-ayush2903) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt]: We never use butterknife in kotlin, remove it. I admit the fact that this pattern is being followed in currently, this file will more probably need a rewrite to eliminate all the butterknife bindings.

Comment (divyank00) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt]: Yeah its true, i just followed the pattern of existing code.

Comment (s-ayush2903) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt]: Building upon the existing caveats and error-prone code obliviously is never a good idea. When you know something better you must implement it instead of just connecting the dots. You can definitely follow the pattern if you're very sure of the fact it is good and safe to use practice.

Comment (divyank00) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt]: Thanks for correcting me😊
Will update the pr soon

**Comment by devansh-299** [comment]
@divyank00 seems like a nice addition. Do resolve the merge conflicts in the pull request and alignment of the qr image and we can merge this!

**Comment by divyank00** [comment]
> @divyank00 seems like a nice addition. Do resolve the merge conflicts in the pull request and alignment of the qr image and we can merge this!

Have resolved the conflicts, what is the expected alignment?

**Comment by devansh-299** [comment]
> 
> 
> > @divyank00 seems like a nice addition. Do resolve the merge conflicts in the pull request and alignment of the qr image and we can merge this!
> 
> Have resolved the conflicts, what is the expected alignment?

@divyank00 the qr code icon should be vertically in the center. Also, I forgot to mention, please avoid using butterknife with Kotlin as pointed out by @s-ayush2903 and remove those comments (_which are not important_). I know they are also present at other permission related places but let's avoid them here.

**Comment by divyank00** [comment]
@devansh-299 @s-ayush2903 Can you please review it.
Have updated the alignment and removed the butterknife

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt [hunk 2]
```diff
@@ -35,13 +45,21 @@ class NewSIActivity : BaseActivity(), StandingInstructionContract.NewSIView {
...
         mPresenter.attachView(this)
+        initView()
     }
 
     override fun setPresenter(presenter: StandingInstructionContract.NewSIPresenter) {
         this.mNewSIPresenter = presenter
     }
 
-    @OnClick(R.id.btn_valid_till)
+    private fun initView(){
```
Comment (devansh-299) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/standinginstruction/ui/NewSIActivity.kt]: There are some code styling issues here. I am nitpicking [here](https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s4.6.2-horizontal-whitespace) but do see this site, it will be a good read.

**Comment by divyank00** [comment]
@devansh-299 yeah, i didnt auto format because some other code was getting distorted, will be careful henceforth.

Have changed it, have a look

**Review by devansh-299 — APPROVED** [review]
Still missed one styling correction, refer to [section 4.1.2](https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s4.1.2-blocks-k-r-style) but nevermind. Nice work by the way!

**Comment by divyank00** [comment]
> Still missed one styling correction, refer to [section 4.1.2](https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s4.1.2-blocks-k-r-style) but nevermind. Nice work by the way!

😅
