### PR TITLE
fix #1507: fix settings visibility & migrated to compose

### LINKED ISSUE #1507: Fix: invisible buttons in settings screen
**Summary:**

Disable button and logout button are not visible in the settings screen

**Steps to reproduce:**

How can we reproduce again the issue?

- just open settings from the top right menu

What did you expect the app to do?

- Display options properly

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
android : 14
device: pixel 7

**Screenshots:**
settings

### PR DESCRIPTION
**Pull request by PratyushSingh07**
## Issue Fix
Fixes #1507 

Screenshot_20240204-214645

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
I have also migrated this screen to compose @therajanmaurya

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt [hunk 1]
```diff
@@ -24,39 +24,46 @@ class SettingsActivity : BaseActivity(), SettingsView {
...
+                    logout = { onLogoutClicked() }
+                )
+            }
+        }
     }
 
-    @OnClick(R.id.btn_logout)
-    fun onLogoutClicked() {
+    private fun onLogoutClicked() {
         val builder = AlertDialog.Builder(this, R.style.AppTheme_Dialog)
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt]: Convert this as well in jetpack compose. First add generic implementation of compose dialog in `core:designsystem` and generic method to directly access the dialog and minimal parameters expose in `core:ui` module and use here.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt [hunk 2]
```diff
@@ -24,39 +24,46 @@ class SettingsActivity : BaseActivity(), SettingsView {
     @Inject
     var mPresenter: SettingsPresenter? = null
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt]: This is very bad code smell, presenter can't be null. Presenter are single truth data source.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt [hunk 3]
```diff
@@ -24,39 +24,46 @@ class SettingsActivity : BaseActivity(), SettingsView {
...
         val alert = builder.create()
         alert.show()
     }
 
-    @OnClick(R.id.btn_disable_account)
-    fun onDisableAccountClicked() {
-        dialogBox.setPositiveListener() { dialog, which -> mSettingsPresenter!!.disableAccount() }
-        dialogBox.setNegativeListener() { dialog, which -> dialog.dismiss() }
+    private fun onDisableAccountClicked() {
+        dialogBox.setPositiveListener { _, _ -> mSettingsPresenter?.disableAccount() }
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsActivity.kt]: Convert DialogBox in jetpack compose.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+@OptIn(ExperimentalMaterial3Api::class)
+@Composable
+fun SettingsScreen(
+    backPress: () -> Unit,
+    disable: () -> Unit,
+    logout: () -> Unit
+) {
+    Scaffold(
+        topBar = {
+            TopAppBar(
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Move it to generic class in `core:designsystem`

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+                title = {
+                    Text(
+                        text = stringResource(id = R.string.settings),
+                        style = TextStyle(
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Move it to `MifosTextStyle` and create generic `MifosText` in `core:designsystem`

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+                            fontSize = 20.sp
+                        )
+                    )
+                },
+                navigationIcon = {
+                    IconButton(onClick = { backPress.invoke() }) {
+                        Icon(
+                            imageVector = Icons.Filled.ArrowBack,
+                            contentDescription = "Back",
+                            tint = Color(0xFF212121)
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Move it to Color in `core:designsystem`

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 7]
```diff
@@ -0,0 +1,159 @@
...
+    ) {
+        Column(
+            modifier = Modifier
+                .fillMaxSize()
+                .background(Color.White)
+                .padding(it)
+        ) {
+            Row(modifier = Modifier.padding(20.dp)) {
+                MifosItemCard(
+                    onClick = { /*TODO*/ },
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: if it is not useful then remove.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 8]
```diff
@@ -0,0 +1,159 @@
...
+                    colors = CardDefaults.cardColors(Color.White)
+                ) {
+                    Text(
+                        text = stringResource(id = R.string.notification_settings),
+                        modifier = Modifier
+                            .fillMaxWidth()
+                            .padding(20.dp),
+                        style = TextStyle(fontSize = 17.sp, color = Color(0xFF212121))
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Move this in MifosTextStyle

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+                }
+            }
+        }
+    }
+
+
+}
+
+@Composable
+fun MifosItemCard(
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Move it in `core:designsystem` and then make utility method in `ui` module.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+        elevation = CardDefaults.cardElevation(
+            defaultElevation = elevation
+        ),
+        colors = colors,
+        content = content
+    )
+}
+
+@Preview(showSystemUi = true)
+@Composable
```
Comment (therajanmaurya) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt:126]: Good work for adding the preview function.

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

**Comment by PratyushSingh07** [comment]
done the requested changes here @therajanmaurya

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+                DialogType.LOGOUT -> R.string.no
+                else -> R.string.empty
+            },
+            onConfirm = {
+                when (currentDialog) {
+                    DialogType.DISABLE_ACCOUNT -> disable()
+                    DialogType.LOGOUT -> logout()
+                    else -> {}
+                }
+                currentDialog = DialogType.NONE
```
Comment (PratyushSingh07) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: I have converted the dialog box to compose @therajanmaurya . I am currently using enums to handle the disable button and logout button. However earlier I had used the below approach to open the dialog box
```
    var showDisableDialog by remember { mutableStateOf(false) }
    var showLogoutDialog by remember { mutableStateOf(false) }

    MifosDialogBox(
        showDialog = showDisableDialog,
        onDismiss = { showDisableDialog = false },
        title = R.string.alert_disable_account,
        message = R.string.alert_disable_account_desc,
        confirmButtonText = R.string.ok,
        dismissButtonText = R.string.cancel,
        onConfirm = { disable.invoke() }
    )

    MifosDialogBox(
        showDialog = showLogoutDialog,
        onDismiss = { showLogoutDialog = false },
        title = R.string.log_out_title,
        confirmButtonText = R.string.yes,
        dismissButtonText = R.string.no,
        onConfirm = { logout.invoke() }
    )
    
    Hence I wanted your opinion on this

**Review by PratyushSingh07 — COMMENTED** [review]
Made the required changes @therajanmaurya

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt (hunk 11 above)
Comment (therajanmaurya) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Approach is good but let's have separate method for logout and disable because it more code with condition rather than separate method.

Comment (PratyushSingh07) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt]: Ok, so I can use the earlier approach?

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt [hunk 12]
```diff
@@ -0,0 +1,129 @@
...
+    backPress: () -> Unit,
+    disable: () -> Unit,
+    logout: () -> Unit
+) {
+    var dialogState by remember { mutableStateOf(DialogState()) }
+
+    DialogManager(
+        dialogState = dialogState,
+        onDismiss = { dialogState = DialogState(type = DialogType.NONE) }
+    )
```
Comment (PratyushSingh07) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt:48]: I have made a generic DialogManager.kt composable using which we can access both the disable and logout button. Please review this @therajanmaurya

**Review by PratyushSingh07 — COMMENTED** [review]
Made some changes for you to review @therajanmaurya

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt (hunk 12 above)
Comment (therajanmaurya) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/settings/ui/SettingsScreen.kt:48]: It's great!

**Review by therajanmaurya — APPROVED** [review]
