### PR TITLE
Fix: Keyboard closes on saving

### LINKED ISSUE #299: The keyboard doesn't slide back down after clicking on the save option
**Summary:**

The keyboard doesn't slide back down after clicking on the save option after editing in the text field in Edit Profile fragament

**Steps to reproduce:**

Go to Profile Activity
Click on Edit text in any field, edit something
Click on save button

**Expected behavior:**

Keyboard should slide down

**Observed behavior:**

The keyboard is not sliding down

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

videotogif_2019 02 13_16 22 28 1

### PR DESCRIPTION
**Pull request by rachittt**
### Issue Fix
Fixes #299 

### GIF
ezgif com-video-to-gif (10)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java [hunk 1]
```diff
@@ -243,15 +243,17 @@ public void hideKeyboard() {
         InputMethodManager imm
                 = (InputMethodManager) getSystemService(Activity.INPUT_METHOD_SERVICE);
         View view = getCurrentFocus();
-        if (view == null && imm != null) {
-            view = new View(this);
+        if (imm != null) {
```
Comment (luckyman20) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/editprofile/ui/EditProfileActivity.java]: If this is the solution, then you can simply put `imm != null` before `&&` and you will be fine.
