### PR TITLE
automate the EditText for date in DebitCardFragment.java

### LINKED ISSUE #1154: Automate the EditText for date in setup UPI pin debit card section
**Summary:**

The Edit Text to put the expiry date of debit card is not automated.

**Steps to reproduce:**

 1. Go to Setup UPI Pin activity.
 2. You can see a two EditText in debit card section one for month and another for year
 3. Try to type a date they both.
 4. You will have to fill month and year separately.

**Expected behavior:**

Those two EditText should work as one so that user don't have to switch.

**Observed behavior:**

Right now those two work separartely.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screen Recording**

https://user-images.githubusercontent.com/56648862/104602572-8c63b480-56a1-11eb-976c-4042d6146dfd.mp4

### PR DESCRIPTION
**Pull request by EGOR-IND**
## Issue Fix
Fixes #1154 

## Screen Recording

https://user-images.githubusercontent.com/56648862/104721995-a65dcf80-5753-11eb-91ec-5799782082c1.mp4

## Description
Automated the date edit text in DebitCardFragment.java linked to fragment_debit_card.xml

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java [hunk 1]
```diff
@@ -74,6 +81,40 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
...
+            @Override
+            public void afterTextChanged(Editable s) {
+
+            }
+        });
+
+        mPeYear.setOnKeyListener(new View.OnKeyListener() {
+            @Override
+            public boolean onKey(View v, int keyCode, KeyEvent event) {
+                Log.d(TAG, "onTextChanged: " + key + " " + mPeYear.length());
```
Comment (divyank00) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java]: Can this line be removed along with imports?

Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java]: Yeah i just added it for testing it actually doesn't contribute in any process, it's for debugging.

**Comment by devansh-299** [comment]
@EGOR-IND can you please link/create an issue describing the problem.

**Comment by EGOR-IND** [comment]
> @EGOR-IND can you please link/create an issue describing the problem.

okay, i'll make one tomorrow.

**Comment by EGOR-IND** [comment]
@devansh-299 I linked an issue please review this PR. Sorry for such a delay it was very unprofessional of me, I was stuck with some college work, You know new semester new headaches.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java (hunk 1 above)
Comment (divyank00) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java]: Yeah, that's why just remove the extra changes😀

**Comment by EGOR-IND** [comment]
@divyank00 finally everything is completed, you don't now man i messed up big time today, I totally messed my local branches but now I can peacefully move forward. **LOL**

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java [hunk 2]
```diff
@@ -44,6 +46,8 @@
     @BindView(R.id.pe_year)
     PinEntryEditText mPeYear;
 
+    boolean key = false;
```
Comment (devansh-299) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java:49]: Working seems fine but @EGOR-IND can you please explain the use of this field in your code and maybe try to give a more meaningful name to this field

Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java:49]: I used this field because when the length of mPeYear becomes zero then we don't want the cursor to go directly on the month field so when it's true then cursor will go to the month field

Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java:49]: Hey @devansh-299 don't merge it i found a small flaw. Let me make some improvements.

Comment (EGOR-IND) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/bank/fragment/DebitCardFragment.java:49]: Hey @devansh-299, now this PR is ready without any flaw and the use of field that you asked for have same use as it has before.

**Comment by EGOR-IND** [comment]
@devansh-299 can you review this, I made the changes it's ready to go, you can ask any doubt you have.
