### PR TITLE
fix: new password can't be the same as old password toast

### LINKED ISSUE #612: fix: no error message shows up when current password is same as new password
**Summary:**
When user wishes to change password, we don't have any mechanism where the user is prompted if the current password is same as the new password where as many apps do have that.

**Steps to reproduce:**

1. Go to Edit Profile
2. Change Password
3. Type your old password in new password and repeat too

**Device and Android version:**
Any

### PR DESCRIPTION
**Pull request by laxyapahuja**
## Issue Fix
Fixes #612 

## Description
Added a toast which shows up if the user enters the same password as the new password.

##
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java [hunk 1]
```diff
@@ -14,9 +14,6 @@
     public static final String TO_EXTERNAL_ID = "to_external_id";
     public static final String RUPEE = "₹";
     public static final String QR_DATA = "qr_data";
-    public static final String MERCHANT_NAME = "merchant_name";
-    public static final String MERCHANT_VPA = "merchant_vpa";
```
Comment (luckyman20) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java]: You have made many unnecessary changes. Please fix that.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java [hunk 2]
```diff
@@ -181,6 +181,8 @@
 
     public static final String ERROR_FIELDS_CANNOT_BE_EMPTY = "Fields cannot be empty";
     public static final String ERROR_VALIDATING_PASSWORD = "Passwords are not the same";
```
Comment (shiv07tiwari) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/utils/Constants.java]: Change this OLD_PASSWORD_NEW_PASSWORD to something more meaningful, which reflects that it is an error message.

**Comment by shiv07tiwari** [comment]
@laxyapahuja Any updates?

**Comment by laxyapahuja** [comment]
> @laxyapahuja Any updates?

fixed :) sorry for replying so late, i just saw the message right now.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/password/presenter/EditPasswordPresenter.java [hunk 3]
```diff
@@ -44,7 +44,9 @@ public void updatePassword(String currentPassword, final String newPassword,
         mEditPasswordView.startProgressBar();
         if (isNotEmpty(currentPassword) && isNotEmpty(newPassword)
                 && isNotEmpty(newPasswordRepeat)) {
-            if (isNewPasswordValid(newPassword, newPasswordRepeat)) {
+            if (currentPassword.equals(newPassword)) {
+                mEditPasswordView.showError(Constants.ERROR_PASSWORDS_CANT_BE_SAME);
```
Comment (rachittt) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/password/presenter/EditPasswordPresenter.java:48]:
```suggestionm
                EditPasswordView.stopProgressBar();
                mEditPasswordView.showError(Constants.ERROR_PASSWORDS_CANT_BE_SAME);
```

Comment (rachittt) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/password/presenter/EditPasswordPresenter.java:48]: please add `EditPasswordView.stopProgressBar()` before `mEditPasswordView.showError(Constants.ERROR_PASSWORDS_CANT_BE_SAME)` so that the progress bar stops and the user is able to see the error message clearly.
