### PR TITLE
Fixes #876 - VPA labeled correctly in ShowQrActivity

### LINKED ISSUE #876: VPA labeled incorrectly as Email in ShowQrActivity
**Summary:**
In `ShowQrActivity` VPA is incorrectly labeled as email. Also after set amount dialog the label disappears.

Screenrecorder-2020-04-08-17-48

### PR DESCRIPTION
**Pull request by dubeyaayush07**
Fixes #876

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java [hunk 1]
```diff
@@ -161,15 +161,15 @@ public void onClick(DialogInterface dialog, int which) {
                     return;
                 }
                 mAmount = amount;
-                tvQrData.setText(qrData + ", " + mAmount);
+                tvQrData.setText(getString(R.string.vpa) + ": " + qrData + ", " + mAmount);
```
Comment (Bhavnaharitsa) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java:164]: The mentors have stated that we dont need the credential there, as it would disturb the process of scanning code.

Comment (dubeyaayush07) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java:164]: It is the same place, after the set amount dialog the QR details are set again that is why we need to set label again too otherwise the whole thing looks inconsistent. The scanning of the code takes place before this and does not utilize the `tvQrData`'s text it only uses the `qrData` which I am not modifying.

Comment (Bhavnaharitsa) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/qr/ui/ShowQrActivity.java:164]: Cool, if it doesn't disrupt :)

**Comment by rachittt** [comment]
@dubeyaayush07 code looks good. can you also post the GIF of the working code for reference before this PR gets merged?

**Comment by dubeyaayush07** [comment]
@rachittt 
Screenrecorder-2020-04-16-13-43

**Comment by rachittt** [comment]
@dubeyaayush07 a little addition that we require here is a field below the `VPA ` which displays the numerical value of the amount that has been set by the user. Kindly make the changes so that the PR can be merged.

**Comment by dubeyaayush07** [comment]
@rachittt **Updated**
Screenrecorder-2020-04-16-16-51

**Comment by luckyman20** [comment]
Thanks @dubeyaayush07 !
