### PR TITLE
fixes #762 - Soft Keyboard hides on clicking anywhere

### LINKED ISSUE #762: Softkeyboard closing only on tapping close button
**Summary:**

Softkeyboard closing only on tapping close/back/dismiss button.

**Steps to reproduce:**

Login Activity
WhatsApp-Video-2020-02-26-at-735

**Expected behavior:**

The keyboard should dismiss on tapping anywhere on the screen other than the Edittext box.

**Device and Android version:**

Huawei Honor 9 Lite
Android Pie 9.1

### PR DESCRIPTION
**Pull request by anubhav11march**
## Issue Fix
Fixes #762 

## Screenshots
gif1

## Description
Soft Keyboard now hides on clicking anywhere and not just on clicking the system back button.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by refactor-droidyy** [comment]
@anubhav11march there is some checkstyle rule violation causing the build to fail.

**Comment by anubhav11march** [comment]
@refactor-droidyy I believe to have followed the exact style of code for Travis building.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java [hunk 1]
```diff
@@ -214,4 +222,12 @@ public void onComplete(@NonNull Task<Void> task) {
                     });
         }
     }
+
+    private void hideSoftKeyboard() {
+        View view = this.getCurrentFocus();
+        if(view != null) {
+            InputMethodManager inputMethodManager = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
```
Comment (jawidMuhammadi) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java]: Your build is failing because of code in line number 229. This line of code contains more than 100 chars, which is a PMD violation. To make your build pass break the line into half.

Comment (anubhav11march) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java]: Hey, thanks. I overlooked this. :)

Comment (anubhav11march) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java]: Looks like that wasn't it. Anyway, I'll look for it.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java [hunk 2]
```diff
@@ -214,4 +222,13 @@ public void onComplete(@NonNull Task<Void> task) {
                     });
         }
     }
+
+    private void hideSoftKeyboard() {
```
Comment (GOVINDDIXIT) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/auth/ui/LoginActivity.java]: @anubhav11march Thanks for the PR! 
Can you use the `hideSoftKeyboard()` method available in the utils instead of creating it again
