### PR TITLE
fix:Amount column in Transfer fragment should accept up to 2 decimal digits in the amount

### LINKED ISSUE #318: Account column in Transfer fragment should accept up to 2 decimal digits in the amount
**Summary:**

Account column in Transfer fragment should accept up to 2 decimal digits in the amount 

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #318 

**Gif:**

videotogif_2019 02 23_10 49 02

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java [hunk 1]
```diff
@@ -111,6 +114,27 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
         mEtMobileNumber.addTextChangedListener(new PhoneNumberFormattingTextWatcher());
+        etAmount.addTextChangedListener(new TextWatcher() {
+            @Override
+            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
+
+            }
+
+            @Override
+            public void onTextChanged(CharSequence s, int start, int before, int count) {
+                if (s.toString().contains(AMOUNT_DECIMAL_SEPARATOR) &&
```
Comment (naman14) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java]: please add documentation
https://github.com/openMF/mobile-wallet/pull/349#discussion_r259775412

Comment (shaliniv16) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/ui/TransferFragment.java]: @naman14 documentation added
