### PR TITLE
Fixed Issue No #1198 Does not show client details.

### LINKED ISSUE #1198: Does not show client details
**Summary:**

The App not showing the client details

**Steps to reproduce:**

Just go to the MainActivity and see here the showclientdetails() function. There is the code that is commented out.

**Expected behavior:**

Show the client details

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by Prashant830**
## Issue Fix
Fixes #1198

## Screenshots
<p>

</p>

## Description
 In mainActivity, mainPresenter, BaseHomeContract interface I am going to remove the `showclientdetails()`  function.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java [hunk 1]
```diff
@@ -17,8 +17,6 @@
 public interface BaseHomeContract {
 
     interface BaseHomeView extends BaseView<BaseHomePresenter> {
-
-        void showClientDetails(Client client);
```
Comment (devansh-299) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java:21]: Since we don't have any methods inside the interface, we can skip it altogether. If any requirement arises for the same in the future, we can always create it again

**Review by devansh-299 — CHANGES_REQUESTED** [review]

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java (hunk 1 above)
Comment (Prashant830) [reply mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java:21]: @devansh-299  if we removed `BaseHomeView` Interface then we also required to removes the  `BaseHomePresenter`  Interface because  `BaseHomeView` Interface extend the property of `BaseHomePresenter`.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java [hunk 2]
```diff
@@ -17,8 +17,6 @@
...
     }
 
     interface BaseHomePresenter extends BasePresenter {
```
Comment (Prashant830) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/home/BaseHomeContract.java:22]: @devansh-299 by chance if we removed both of the interfaces (`BaseHomeView` , `BaseHomePresenter`).
then where we add `void fetchClientDetails();` method??

**Review by devansh-299 — APPROVED** [review]
