### PR TITLE
fix: fixed view receipt

### LINKED ISSUE #1329: Window Leak in Receipt Activity
**Summary:**

`android.view.WindowLeaked: Activity org.mifos.mobilewallet.mifospay.receipt.ui.ReceiptActivity has leaked window DecorView@1d97b30[ReceiptActivity] that was originally added here`

Receipt View - has window leak

**Steps to reproduce:**

**Device and Android version:**

Pixel 4 Emulator Running on API 29

### PR DESCRIPTION
**Pull request by alphaNewrex**
## Issue Fix
Fixes #1329 

## Description

Updated the hideProgressDialog funtion

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by alphaNewrex** [comment]
@devansh-299 can you please review this PR.

File: mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java [hunk 1]
```diff
@@ -88,7 +88,7 @@ public void showProgressDialog(String message) {
     @Override
     public void hideProgressDialog() {
         if (progressDialog != null) {
-            progressDialog.hide();
+            progressDialog.dismiss();
```
Comment (Prashant830) [inline mifospay/src/main/java/org/mifos/mobilewallet/mifospay/base/BaseActivity.java:91]: why u added this  in the `public void hideProgressDialog()` at `BaseActivity.java.` if u want to add progressBar.dismiss() then just create `public void hideProgressDialog()` method.
@devansh-299  please check it..
