### PR TITLE
CI: Added a new job for checkstyle inspection

### LINKED ISSUE #1200: CI: GH-Actions do not fail on incorrect file formatting
**Summary:**
Our GH-Actions do not fail the CI on poor/weak file formattings 

**Steps to reproduce:**
Poorly indent the file via adding needless spaces and commit 'em in a PR, notice that any of the checks does not fail.

**Expected behavior:**
Failure of CI

**Observed behavior:**
Green checks

**Device and Android version:**
CI

**Screenshots:**
NA

### PR DESCRIPTION
**Pull request by s-ayush2903**
## Issue Fix
Fixes #1200 

## Screenshots
NA

## Description
Wrote a new job that verifies if the checkstyle is being followed in the PR

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/FineractApiManager.java [hunk 1]
```diff
@@ -37,12 +37,12 @@
 
     public static final String DEFAULT = "default";
     public static final String BASIC = "Basic ";
-    private static BaseURL baseUrl = new BaseURL();
+        private static BaseURL baseUrl = new BaseURL();
```
Comment (devansh-299) [inline core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/FineractApiManager.java]: Were these changes required to make the build pass on latest changes? They seem odd to me.

Comment (s-ayush2903) [reply core/src/main/java/org/mifos/mobilewallet/core/data/fineract/api/FineractApiManager.java]: Ah, it is just to test if the workflow runs as expected, I would revert these changes

**Review by devansh-299 — APPROVED** [review]
Great @s-ayush2903! merging this
